import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/react-query";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} flex min-h-dvh flex-col font-sans antialiased`}
      >
        <ReactQueryProvider>
          <Header />
          <main className="mx-auto my-8 w-full max-w-[1440px] flex-1">
            {children}
          </main>
          <Footer />
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
